### ISSUE TITLE
Driver-Pulsar Issue if TLS Empty

### ISSUE THREAD

**Issue by tlandle** [openmessaging/openmessaging-benchmark#104]
Driver pulsar returns an error in benchmark-worker if the TLS authentication field is empty in pulsar.yaml.

**Comment by Hellojungle** [comment]
@tlandle Could you show me the TLS configurations of your pulsar.yaml?

**Comment by tlandle** [comment]
It is the same as the example in driver-pulsar/pulsar.yaml except with 2 ackquorum rather than 3.

**Comment by tlandle** [comment]
The lack of TLS authentication field breaks it. If I comment out lines 
 /*if (!config.client.authentication.plugin.isEmpty()) {
            clientBuilder.authentication(config.client.authentication.plugin, config.client.authentication.data);
            pulsarAdminBuilder.authentication(config.client.authentication.plugin, config.client.authentication.data);
        }*/

It will run.

**Comment by dreamcatchernick** [comment]
same issue here. 

throw null pointer exception when i run the benchmark. i add "" in the config file pulsar-effectively-once.yaml and pulsar.yaml

**Comment by Hellojungle** [comment]
@tlandle @dreamcatchernick Pulsar config has been updated, you can try again.

**Comment by tlandle** [comment]
LGTM
