### ISSUE TITLE
Broken link in README.md file

### ISSUE THREAD

**Issue by david-streamlio** [openmessaging/openmessaging-benchmark#33]
There is a broken link on main README page...the RocketMQ link;  https://github.com/openmessaging/openmessaging-benchmark/blob/master/driver-rocketmq/README.md returns a 404....

**Comment by vongosling** [comment]
@david-streamlio could you please re-check the link?

**Comment by david-streamlio** [comment]
I still get a 404. Even after I sign in to github

**Comment by srkukarni** [comment]
Can confirm that I too see a 404.

**Comment by sijie** [comment]
@vongosling I can't access the page as well.

**Comment by sijie** [comment]
@vongosling there is no README in rocketmq driver: https://github.com/openmessaging/openmessaging-benchmark/tree/master/driver-rocketmq

**Comment by Hellojungle** [comment]
Where to find the broken link? I only see a link to https://rocketmq.apache.org/  for the RocketMQ on main README page.

**Comment by vongosling** [comment]
@sijie @david-streamlio try again？

**Comment by david-streamlio** [comment]
Looks good.  The link works
