### ISSUE TITLE
SSL Connection

### ISSUE THREAD

**Issue by waewoo** [openmessaging/openmessaging-benchmark#57]
Hello,

Can you tell me how we can configure your tools to connect in SSL to KAFKA brokers?

Thank you

**Comment by merlimat** [comment]
@waewoo Currently the Ansible scripts are not configuring TLS in Kafka. It would be great to add that option though.

If you want to just connect to an existing Kafka cluster, you should be able to change the configuration in `driver-kafka/kafka.yaml` to add the proper Kafka client config.

**Comment by waewoo** [comment]
OK Thanks for information.
