### ISSUE TITLE
The bookkeeper and distributedlog-core-shaded versions are not available in central maven

### ISSUE THREAD

**Issue by zhouxinyu** [openmessaging/openmessaging-benchmark#64]
bookkeeper.version: 4.7.0-SNAPSHOT
distributedlog-core-shaded: 4.7.0-SNAPSHOT

Couldn't find the artifacts of these two versions in central maven.

**Comment by vjanelle** [comment]
@merlimat you can probably close this then

**Comment by merlimat** [comment]
Thanks @vjanelle
