### ISSUE TITLE
Apache Pulsar Benchmark @AWS: error 

### ISSUE THREAD

**Issue by iharijono** [openmessaging/openmessaging-benchmark#74]
After following the instruction on http://openmessaging.cloud/docs/benchmarks/pulsar/, I got an error when running a benchmark (any benchmark will do for ex. workloads/simple_workload.yaml).
I checked all the instances are up and communicating well.

Has anyone experienced the same?
Any hints are greatly appreciated.

Thanks,
Indra

20:49:56.371 [main] INFO - Workers list - producers: [http://10.0.0.244:8080, http://10.0.0.175:8080]
20:49:56.371 [main] INFO - Workers list - consumers: [http://10.0.0.225:8080, http://10.0.0.11:8080]
20:49:56.375 [main] INFO - --------------- WORKLOAD : 1 producer / 3 consumers on 100 topics --- DRIVER : Pulsar---------------
20:49:57.999 [main] INFO - Created 100 topics in 31.2175 ms
20:49:58.526 [AsyncHttpClient-2-4] ERROR - Failed to do HTTP post request to http://10.0.0.11:8080/create-consumers -- code: 500
20:49:58.592 [AsyncHttpClient-2-3] ERROR - Failed to do HTTP post request to http://10.0.0.225:8080/create-consumers -- code: 500
20:49:58.593 [main] ERROR - Failed to run the workload '1 producer / 3 consumers on 100 topics' for driver 'driver-pulsar/pulsar.yaml'
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_181]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[?:1.8.0_181]
...... DELETED

**Comment by sijie** [comment]
@iharijono : I think the problem comes from between driver (driver is the controller that sets up the benchmark) and workers (workers are the agents that runs producers and consumers). It seems that the driver attempts to communicate with workers to start consumers, but it fails to start the consumers.

can you go to one of the worker nodes (10.0.0.225 and 10.0.0.11) and run "journalctl -u benchmark-worker.service" to view the worker logs?

**Comment by iharijono** [comment]
@sijie , Thank you for your comment, 

I rerun and got the worker logs (see below), everything looks ok, no errors or whatsoever.


Here is again the error:
=====================

05:23:15.880 [main] INFO - Workers list - producers: [http://10.0.0.26:8080, http://10.0.0.171:8080]
05:23:15.881 [main] INFO - Workers list - consumers: [http://10.0.0.93:8080, http://10.0.0.203:8080]
05:23:15.884 [main] INFO - --------------- WORKLOAD : Simple Workload 1 producer on 1 topic --- DRIVER : Pulsar---------------
05:23:18.561 [main] INFO - Created 1 topics in 1073.071875 ms
05:23:19.010 [AsyncHttpClient-2-3] ERROR - Failed to do HTTP post request to http://10.0.0.93:8080/create-consumers -- code: 500
05:23:19.011 [main] ERROR - Failed to run the workload 'Simple Workload 1 producer on 1 topic' for driver 'driver-pulsar/pulsar.yaml'
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_181]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[?:1.8.0_181]
.........................
..........................

And here is the log from http://10.0.0.203 (one of the worker):
==============================================

[ec2-user@ip-10-0-0-203 ~]$ journalctl -u benchmark-worker.service
-- Logs begin at Wed 2018-08-01 04:33:50 UTC, end at Wed 2018-08-01 05:25:22 UTC. --
Aug 01 05:07:12 ip-10-0-0-203.us-west-2.compute.internal systemd[1]: Started Pulsar Broker.
Aug 01 05:07:12 ip-10-0-0-203.us-west-2.compute.internal systemd[1]: Starting Pulsar Broker...
Aug 01 05:07:14 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: SLF4J: Class path contains multiple SLF4J bindings.
Aug 01 05:07:14 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: SLF4J: Found binding in [jar:file:/opt/benchmark/lib/org.apache.logging.log4j-log4
Aug 01 05:07:14 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: SLF4J: Found binding in [jar:file:/opt/benchmark/lib/ch.qos.logback-logback-classi
Aug 01 05:07:14 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
Aug 01 05:07:14 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
Aug 01 05:07:14 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: 05:07:14.637 [main] INFO - Logging initialized @2105ms to org.eclipse.jetty.util.l
Aug 01 05:07:14 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: 05:07:14.717 [main] INFO - jetty-9.4.8.v20171121, build timestamp: 2017-11-21T21:2
Aug 01 05:07:14 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: 05:07:14.741 [main] INFO - Started o.e.j.s.ServletContextHandler@563f38c4{/,null,A
Aug 01 05:07:14 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: 05:07:14.755 [main] INFO - Started ServerConnector@3f191845{HTTP/1.1,[http/1.1]}{0
Aug 01 05:07:14 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: 05:07:14.755 [main] INFO - Started @2227ms
Aug 01 05:07:14 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: 05:07:14.764 [main] INFO - Started Prometheus stats endpoint at 0.0.0.0:8081
Aug 01 05:07:14 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: 05:07:14.784 [main] INFO - Starting benchmark with config: {
Aug 01 05:07:14 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: "httpPort" : 8080,
Aug 01 05:07:14 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: "statsPort" : 8081
Aug 01 05:07:14 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: }
Aug 01 05:07:14 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: 05:07:14.823 [main] INFO -
Aug 01 05:07:14 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: _________________________________________
Aug 01 05:07:14 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: |        _                  _ _           |
Aug 01 05:07:14 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: |       | | __ ___   ____ _| (_)_ __      |
Aug 01 05:07:14 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: |    _  | |/ _` \ \ / / _` | | | '_ \     |
Aug 01 05:07:14 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: |   | |_| | (_| |\ V / (_| | | | | | |    |
Aug 01 05:07:14 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: |    \___/ \__,_| \_/ \__,_|_|_|_| |_|    |
Aug 01 05:07:14 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: |_________________________________________|
Aug 01 05:07:14 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: |                                         |
Aug 01 05:07:14 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: |    https://javalin.io/documentation     |
Aug 01 05:07:14 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: |_________________________________________|
Aug 01 05:07:14 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: 05:07:14.825 [main] INFO - Starting Javalin ...
Aug 01 05:07:14 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: 05:07:14.832 [main] INFO - jetty-9.4.8.v20171121, build timestamp: 2017-11-21T21:2
Aug 01 05:07:14 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: 05:07:14.840 [main] INFO - DefaultSessionIdManager workerName=node0
Aug 01 05:07:14 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: 05:07:14.840 [main] INFO - No SessionScavenger set, using defaults
Aug 01 05:07:14 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: 05:07:14.840 [main] INFO - Scavenging every 660000ms
Aug 01 05:07:14 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: 05:07:14.841 [main] INFO - Started i.j.e.j.start$httpHandler$1@f627d13{/,null,AVAI
Aug 01 05:07:14 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: 05:07:14.842 [main] INFO - Started o.e.j.s.ServletContextHandler@352ff4da{/,null,A
Aug 01 05:07:14 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: 05:07:14.843 [main] INFO - Started ServerConnector@2e32ccc5{HTTP/1.1,[http/1.1]}{0
Aug 01 05:07:14 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: 05:07:14.843 [main] INFO - Started @2315ms
Aug 01 05:07:14 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: 05:07:14.843 [main] INFO - Jetty is listening on: [http://localhost:8080]
Aug 01 05:07:14 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: 05:07:14.843 [main] INFO - Javalin has started \o/
Aug 01 05:23:16 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: 05:23:16.043 [qtp575935098-24] INFO - Stop All
Aug 01 05:23:16 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: 05:23:16.214 [qtp575935098-29] INFO - Driver: {
Aug 01 05:23:16 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: "name" : "Pulsar",
Aug 01 05:23:16 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: "driverClass" : "io.openmessaging.benchmark.driver.pulsar.PulsarBenchmarkDriver"
Aug 01 05:23:16 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: }
Aug 01 05:23:16 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: 05:23:16.429 [qtp575935098-29] INFO - Pulsar driver configuration: {
Aug 01 05:23:16 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: "client" : {
Aug 01 05:23:16 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: "serviceUrl" : "pulsar://10.0.0.178:6650/",
Aug 01 05:23:16 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: "httpUrl" : "http://10.0.0.178:8080/",
Aug 01 05:23:16 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: "ioThreads" : 8,
Aug 01 05:23:16 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: "connectionsPerBroker" : 8,
Aug 01 05:23:16 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: "namespacePrefix" : "benchmark/local/ns",
Aug 01 05:23:16 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: "topicType" : "persistent",
Aug 01 05:23:16 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: "persistence" : {
Aug 01 05:23:16 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: "ensembleSize" : 3,
Aug 01 05:23:16 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: "writeQuorum" : 3,
Aug 01 05:23:16 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: "ackQuorum" : 2,
Aug 01 05:23:16 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: "deduplicationEnabled" : false
Aug 01 05:23:16 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: }
Aug 01 05:23:16 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: },
Aug 01 05:23:16 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: "producer" : {
Aug 01 05:23:16 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: "batchingEnabled" : true,
Aug 01 05:23:16 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: "blockIfQueueFull" : true,
Aug 01 05:23:16 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: "batchingMaxPublishDelayMs" : 1,
Aug 01 05:23:16 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: "pendingQueueSize" : 10000
Aug 01 05:23:16 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: }
Aug 01 05:23:16 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: }
Aug 01 05:23:16 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: 05:23:16.717 [qtp575935098-29] INFO - Set Pulsar client configuration: {
Aug 01 05:23:16 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: "authentication" : {
Aug 01 05:23:16 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: "authData" : {
Aug 01 05:23:16 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: "commandData" : null,
Aug 01 05:23:16 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: "tlsCertificates" : null,
Aug 01 05:23:16 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: "tlsPrivateKey" : null,
Aug 01 05:23:16 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: "httpAuthType" : null,
Aug 01 05:23:16 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: "httpHeaders" : null
Aug 01 05:23:16 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: },
Aug 01 05:23:16 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: "authMethodName" : "none"
Aug 01 05:23:16 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: },
Aug 01 05:23:16 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: "operationTimeoutMs" : 30000,
Aug 01 05:23:16 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: "statsIntervalSeconds" : 0,
Aug 01 05:23:16 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: "connectionsPerBroker" : 8,
Aug 01 05:23:16 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: "useTcpNoDelay" : true,
Aug 01 05:23:16 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: "useTls" : false,
Aug 01 05:23:16 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: "tlsTrustCertsFilePath" : "",
Aug 01 05:23:16 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: "tlsAllowInsecureConnection" : false,
Aug 01 05:23:16 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: "tlsHostnameVerificationEnable" : false,
Aug 01 05:23:16 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: "concurrentLookupRequest" : 50000,
Aug 01 05:23:16 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: "maxNumberOfRejectedRequestPerConnection" : 50,
Aug 01 05:23:16 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: "ioThreads" : 8,
Aug 01 05:23:16 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: "listenerThreads" : 1
Aug 01 05:23:16 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: }
Aug 01 05:23:16 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: 05:23:16.941 [qtp575935098-29] INFO - Created Pulsar client for service URL pulsar
Aug 01 05:23:17 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: 05:23:17.085 [qtp575935098-29] INFO - Created Pulsar admin client for HTTP URL htt
Aug 01 05:23:17 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: 05:23:17.096 [qtp575935098-29] INFO - Set producer configuration: {
Aug 01 05:23:17 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: "producerName" : null,
Aug 01 05:23:17 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: "sendTimeoutMs" : 30000,
Aug 01 05:23:17 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: "blockIfQueueFull" : true,
Aug 01 05:23:17 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: "maxPendingMessages" : 10000,
Aug 01 05:23:17 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: "maxPendingMessagesAcrossPartitions" : 50000,
Aug 01 05:23:17 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: "hashingScheme" : "JavaStringHash",
Aug 01 05:23:17 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: "batchingMaxPublishDelayMs" : 1,
Aug 01 05:23:17 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: "batchingMaxMessages" : 1000,
Aug 01 05:23:17 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: "batchingEnabled" : true,
Aug 01 05:23:17 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: "cryptoKeyReader" : null,
Aug 01 05:23:17 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: "encryptionKeys" : null,
Aug 01 05:23:17 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: "compressionType" : "NONE",
Aug 01 05:23:17 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: "initialSequenceId" : {
Aug 01 05:23:17 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: "present" : false
Aug 01 05:23:17 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: },
Aug 01 05:23:17 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: "properties" : { },
Aug 01 05:23:17 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: "cryptoFailureAction" : "FAIL",
Aug 01 05:23:17 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: "messageRoutingMode" : "SinglePartition",
Aug 01 05:23:17 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: "messageRouter" : null,
Aug 01 05:23:17 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: "encryptionEnabled" : false
Aug 01 05:23:17 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: }
Aug 01 05:23:17 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: 05:23:17.354 [qtp575935098-29] INFO - Created Pulsar property benchmark with allow
Aug 01 05:23:17 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: 05:23:17.401 [qtp575935098-29] INFO - Created Pulsar namespace benchmark/local/ben
Aug 01 05:23:17 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: 05:23:17.470 [qtp575935098-29] INFO - Applied persistence configuration for namesp
Aug 01 05:23:17 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: "ensembleSize" : 3,
Aug 01 05:23:17 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: "writeQuorum" : 3,
Aug 01 05:23:17 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: "ackQuorum" : 2,
Aug 01 05:23:17 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: "deduplicationEnabled" : false
Aug 01 05:23:17 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: }
Aug 01 05:23:19 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: 05:23:19.015 [qtp575935098-30] INFO - Stop All
Aug 01 05:23:19 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: 05:23:19.138 [qtp575935098-30] INFO - Shutting down Pulsar benchmark driver
Aug 01 05:23:19 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: 05:23:19.138 [qtp575935098-30] INFO - Client closing. URL: 10.0.0.178:6650
Aug 01 05:23:19 ip-10-0-0-203.us-west-2.compute.internal benchmark-worker[12474]: 05:23:19.145 [qtp575935098-30] INFO - Pulsar benchmark driver successfully shut do

**Comment by iharijono** [comment]
@sijie : I investigated again by reading the java codes. The problem is between Benchmark (that is invoked from the script under bin and uses driver 'pulsar') and the Benchmark worker (the one string Javalin http server).
For some reason Benchmark worker (with Javalin)  return code '505' and shutdown ????

Can someone help? anyone has successfully run this basic test with AWS???

**Comment by sijie** [comment]
@iharijono I had run the test a few months ago. so there might be something changed recently. I will spend some time tomorrow on debugging this. will get back to you soon.

**Comment by iharijono** [comment]
Hi,

I rerun again the benchmark and @sijie is right.
There is exception in creating consumer:
here is the output "journalctl -u benchmark-worker.service" in the worker:


....
....
Aug 02 00:47:12 ip-10-0-0-186.us-west-2.compute.internal benchmark-worker[20086]: 00:47:12.795 [pulsar-client-io-3-5] INFO - [persistent://benchmark/local/ns-IFGO0LY/test-t0i_wUc-0000-partition-9] [sub-000] Closed Consumer (not connected)
Aug 02 00:47:12 ip-10-0-0-186.us-west-2.compute.internal benchmark-worker[20086]: 00:47:12.795 [pulsar-client-io-3-5] INFO - [persistent://benchmark/local/ns-IFGO0LY/test-t0i_wUc-0000] [sub-000] Closed Partitioned Consumer
Aug 02 00:47:12 ip-10-0-0-186.us-west-2.compute.internal benchmark-worker[20086]: 00:47:12.796 [pulsar-client-io-3-5] ERROR - [persistent://benchmark/local/ns-IFGO0LY/test-t0i_wUc-0000] [sub-000] Could not create partitioned consumer.
Aug 02 00:47:12 ip-10-0-0-186.us-west-2.compute.internal benchmark-worker[20086]: org.apache.pulsar.client.api.PulsarClientException$BrokerPersistenceException: org.apache.bookkeeper.mledger.ManagedLedgerException: Not enough non-faulty bookies available
Aug 02 00:47:12 ip-10-0-0-186.us-west-2.compute.internal benchmark-worker[20086]: at org.apache.pulsar.client.impl.ClientCnx.getPulsarClientException(ClientCnx.java:610) ~[org.apache.pulsar-pulsar-client-original-1.22.0-incubating.jar:1.22.0-incubating]
Aug 02 00:47:12 ip-10-0-0-186.us-west-2.compute.internal benchmark-worker[20086]: at org.apache.pulsar.client.impl.ClientCnx.handleError(ClientCnx.java:424) [org.apache.pulsar-pulsar-client-original-1.22.0-incubating.jar:1.22.0-incubating]
Aug 02 00:47:12 ip-10-0-0-186.us-west-2.compute.internal benchmark-worker[20086]: at org.apache.pulsar.common.api.PulsarDecoder.channelRead(PulsarDecoder.java:148) [org.apache.pulsar-pulsar-common-1.22.0-incubating.jar:1.22.0-incubating]
Aug 02 00:47:12 ip-10-0-0-186.us-west-2.compute.internal benchmark-worker[20086]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [io.netty-netty-all-4.1.12.Final.jar:4.1.12.Final]
Aug 02 00:47:12 ip-10-0-0-186.us-west-2.compute.internal benchmark-worker[20086]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [io.netty-netty-all-4.1.12.Final.jar:4.1.12.Final]
Aug 02 00:47:12 ip-10-0-0-186.us-west-2.compute.internal benchmark-worker[20086]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [io.netty-netty-all-4.1.12.Final.jar:4.1.12.Final]
Aug 02 00:47:12 ip-10-0-0-186.us-west-2.compute.internal benchmark-worker[20086]: at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [io.netty-netty-all-4.1.12.Final.jar:4.1.12.Final]
Aug 02 00:47:12 ip-10-0-0-186.us-west-2.compute.internal benchmark-worker[20086]: at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [io.netty-netty-all-4.1.12.Final.jar:4.1.12.Final]
Aug 02 00:47:12 ip-10-0-0-186.us-west-2.compute.internal benchmark-worker[20086]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [io.netty-netty-all-4.1.12.Final.jar:4.1.12.Final]
Aug 02 00:47:12 ip-10-0-0-186.us-west-2.compute.internal benchmark-worker[20086]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [io.netty-netty-all-4.1.12.Final.jar:4.1.12.Final]
Aug 02 00:47:12 ip-10-0-0-186.us-west-2.compute.internal benchmark-worker[20086]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [io.netty-netty-all-4.1.12.Final.jar:4.1.12.Final]
Aug 02 00:47:12 ip-10-0-0-186.us-west-2.compute.internal benchmark-worker[20086]: at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) [io.netty-netty-all-4.1.12.Final.jar:4.1.12.Final]
Aug 

......
......

But I still don't know how to fix it. I guess it is configuration problem, any thoughts???

Thanks,
Indra

**Comment by sijie** [comment]
@iharijono sorry for late response. was busy with Pulsar 2.1.0 release. 

> org.apache.pulsar.client.api.PulsarClientException$BrokerPersistenceException: org.apache.bookkeeper.mledger.ManagedLedgerException: Not enough non-faulty bookies available

so I think the problem is bookies are not started correctly. were you running the ansible scripts twice? the problem does sound like you run ansible scripts twice. if you don't mind, can you destroy your cluster first and re-do the steps?

**Comment by iharijono** [comment]
Hi Sijie,Thanks for responding. Actually I found the problem. Actually 2 problems. It was in the template/broker.conf and template/zoo.conf
I am wondering that no one has produced the error???
using current template/zoo.conf, won't let zookeepers come up correctly. 
using current template/broker.conf will crash benchmark-service.
I have fixed the issue and could reproduce the errors.  Would you like me to give it back to you/community? 
Another question : I was running workloads backlog*, it never terminate???? It doesn't matter how many minutes I define in the yaml files??
Running them on AWS could be expensive if we could "hard" stop the benchmark. 
Let me know what you think.

Thanks, Indra


Sent from Yahoo Mail on Android 
 
  On Mon, Aug 6, 2018 at 4:42 PM, Sijie Guo<notifications@github.com> wrote:   
@iharijono sorry for late response. was busy with Pulsar 2.1.0 release.


org.apache.pulsar.client.api.PulsarClientException$BrokerPersistenceException: org.apache.bookkeeper.mledger.ManagedLedgerException: Not enough non-faulty bookies available


so I think the problem is bookies are not started correctly. were you running the ansible scripts twice? the problem does sound like you run ansible scripts twice. if you don't mind, can you destroy your cluster first and re-do the steps?

**Comment by sijie** [comment]
@iharijono 

glad that you have figured out the problem.

> I am wondering that no one has produced the error???

hard to tell :( people might be hitting same issues and giving up. for us, we might be using some internal branches (catching up with latest pulsar) on running the tests, which might be the reason why we haven't caught this issue. There is one task on upgrading pulsar to latest 2.1.0, I will probably use that chance to make sure we have everything in-sync back to this repo.

>  I have fixed the issue and could reproduce the errors.  Would you like me to give it back to you/community? 

yeah, if you can create a PR to fix the issues, that would be great!

> I was running workloads backlog*, it never terminate???? It doesn't matter how many minutes I define in the yaml files??

oh it should be terminating after the specified time. although I guess, it might be doing draining the backlog, that cause the driver doesn't terminate correctly. do you have a huge backlog to drain?
