### ISSUE TITLE
Update Pulsar client to 2.1.0

### ISSUE THREAD

**Issue by jiazhai** [openmessaging/openmessaging-benchmark#75]
Since Pulsar has already released, would like to update Pulsar client to latest verison

**Comment by vongosling** [comment]
@jiazhai @merlimat @sijie IMO, it's time to separate the benchmark API from the project. I would like to call for discussion in the next week, hoping to see you.

**Comment by vongosling** [comment]
@jiazhai welcome to pr it

**Comment by jiazhai** [comment]
close this, since it is already in 2.1.1
