### ISSUE TITLE
RabbitMQ sendAsync is not asynchronous

### ISSUE THREAD

**Issue by Hellojungle** [openmessaging/openmessaging-benchmark#86]
SendAsync is waiting for confirm each time and the publish rate is 3000msg/s in 1-topic-1-partion-1kb workload

**Comment by merlimat** [comment]
The problem is that in RabbitMQ there's no way to send asynchronously and have a callback/future to track when the message is published.

If we avoid to wait  for confirmation after each message, it would be a completely different semantic guarantee compared to other messaging systems.

**Comment by Hellojungle** [comment]
Maybe we can do publish and confirm in a executor thread during sendAsync.
