### ISSUE TITLE
Add NATS driver

### ISSUE THREAD

**Issue by Hellojungle** [openmessaging/openmessaging-benchmark#89]
Nats is a simple, high performance open source messaging system for cloud native applications, IoT messaging, and microservices architectures.  And I think providing a nats driver is meaningful

**Comment by ColinSullivan1** [comment]
We're glad to see an issue for adding NATS!

Please let us know how we can help.  Benchmark code can be tricky, so I'd suggest looking at our [java benchmark code](https://github.com/nats-io/java-nats/tree/master/src/examples/java/io/nats/examples/benchmark) as a reference.  We'd be happy to help advise and review.

**Comment by Hellojungle** [comment]
@ColinSullivan1 Thanks for your attention!

**Comment by Hellojungle** [comment]
@ColinSullivan1 Thanks for your attention!
I think NATS presents a special architecture and it is quite meaningful to add NATS driver for openmessaging-benchmark. 
In my opinion, it is essential and vital for this project to display advantages of different messaging systems and their special scenarios.

**Comment by vongosling** [comment]
@ColinSullivan1 Let's work together for the nats driver. I have merged @Hellojungle your initial works on nat. would like to polish here in the following days.

**Comment by ColinSullivan1** [comment]
@vongosling , sounds good!
